env:
  browser: true
  es6: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true
plugins:
  - vue
rules: {}
