services:
  frontend:
    build: ./frontend
    image: deadlynote:frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    command: run serve

  backend:
    build: ./backend
    image: deadlynote:backend
    depends_on:
    - redis
    volumes:
    - ./backend:/usr/src/api
    - /usr/src/backend/node_modules
    command: node index.js

  redis:
    image: redis:7-alpine

networks:
  default:
    external: true
    name: deadlynote_proxy
