services:
  frontend:
    build: ./frontendv2
    image: noteorious:frontend
    volumes:
      - /app/node_modules
      - /app/dist
    ports:
      - '4200:80'
    command: nginx -g "daemon off;"
    depends_on:
      - backend

  backend:
    build: ./backendv2
    image: noteorious:backend
    volumes:
      - /app/.venv
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    depends_on:
    - redis

  redis:
    image: redis:7-alpine

networks:
  default:
    name: noteorious
